### ISSUE TITLE
AssertionError: Error Domain=MTLLibraryErrorDomain Code=1 "Invalid library file" right after installing and running test program

### ISSUE THREAD

**Issue by rozim** [tinygrad/tinygrad#2535] opened 2023-12-01 06:27 UTC
I just installed tinygrad based on the instructions at https://github.com/tinygrad/tinygrad and ran a quick program and it failed with `AssertionError: Error Domain=MTLLibraryErrorDomain Code=1 "Invalid library file"`

Command and output:

```

(base) dave@macbook-pro tinygrad % DEBUG=3 python3 -c "from tinygrad import Tensor;
N = 1024; a, b = Tensor.rand(N, N), Tensor.rand(N, N);
c = (a.reshape(N, 1, N) * b.permute(1,0).reshape(1, N, N)).sum(axis=2);
print((c.numpy() - (a.numpy() @ b.numpy())).mean())"

***      rand METAL    seed 1701411349  shape 1048576 dtype dtypes.float
***      rand METAL    seed 1701411350  shape 1048576 dtype dtypes.float
  0 ━┳ STORE MemBuffer(idx=0, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(1024, 1024, 1), strides=(1024, 1, 0), offset=0, mask=None, contiguous=True),)))
  1  ┗━┳ SUM (1024, 1024, 1)
  2    ┗━┳ MUL 
  3      ┣━━ LOAD MemBuffer(idx=1, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(1024, 1024, 1024), strides=(1024, 0, 1), offset=0, mask=None, contiguous=False),)))
  4      ┗━━ LOAD MemBuffer(idx=2, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(1024, 1024, 1024), strides=(0, 1, 1024), offset=0, mask=None, contiguous=False),)))
TENSOR CORES [(1, 1024, 1)] [(0, 1024, 1024)] tensor_core<METAL, [8, 8, 8], dtypes.float, dtypes.float>
3 alias 1: idxs= [Variable('gidx0', 0, 31), NumNode(0), NumNode(0), Variable('lidx3', 0, 1), NumNode(0), ((Variable('lidx4', 0, 15)//2)%4), NumNode(0), Variable('ridx7', 0, 127), (((Variable('lidx4', 0, 15)%2)*2)+((Variable('lidx4', 0, 15)//8)*4)+Variable('None', 0, 1)), NumNode(0), Variable('None', 0, 3), NumNode(0)]
4 alias 2: idxs= [NumNode(0), Variable('gidx1', 0, 7), Variable('lidx2', 0, 3), NumNode(0), (Variable('lidx4', 0, 15)//8), NumNode(0), (Variable('lidx4', 0, 15)%2), Variable('ridx7', 0, 127), (((Variable('lidx4', 0, 15)//2)%4)+(Variable('lidx3', 0, 1)*4)), Variable('None', 0, 1), NumNode(0), Variable('None', 0, 3)]
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/Users/dave/Projects/tinygrad/tinygrad/tensor.py", line 126, in numpy
    return self.detach().cast(dtypes.from_np(self.dtype.np)).contiguous().to('CPU').realize().lazydata.realized.toCPU().astype(self.dtype.np, copy=True).reshape(self.shape)
  File "/Users/dave/Projects/tinygrad/tinygrad/tensor.py", line 105, in realize
    run_schedule(self.lazydata.schedule())
  File "/Users/dave/Projects/tinygrad/tinygrad/realize.py", line 38, in run_schedule
    Device[si.out.device].get_runner(si.ast).exec([si.out.realized] + [x.realized for x in si.inputs], si.var_vals)
  File "/Users/dave/Projects/tinygrad/tinygrad/device.py", line 229, in get_runner
    def get_runner(self, ast:LazyOp) -> CompiledASTRunner: return self.to_program(_get_optimized_linearizer(self.linearizer_opts, ast))
  File "/Users/dave/Projects/tinygrad/tinygrad/device.py", line 226, in to_program
    return CompiledASTRunner(k.ast, k.name, src, k.global_size, k.local_size, runtime_args).build(self.compiler, self.runtime)
  File "/Users/dave/Projects/tinygrad/tinygrad/device.py", line 197, in build
    self.clprg = runtime(self.name, self.lib, self.bufcount, len(self.vars))
  File "/Users/dave/Projects/tinygrad/tinygrad/runtime/ops_metal.py", line 25, in __init__
    self.library = unwrap2(self.device.device.newLibraryWithData_error_(data, None))
  File "/Users/dave/Projects/tinygrad/tinygrad/helpers.py", line 45, in unwrap2
    assert err is None, str(err)
AssertionError: Error Domain=MTLLibraryErrorDomain Code=1 "Invalid library file" UserInfo={NSLocalizedDescription=Invalid library file}
```

System:
Macbook, 16G
Sonoma 14.1.1

From System Info Graphics/Displays
```
Apple M1 Pro:

  Chipset Model:	Apple M1 Pro
  Type:	GPU
  Bus:	Built-In
  Total Number of Cores:	16
  Vendor:	Apple (0x106b)
  Metal Support:	Metal 3
  Displays:
Color LCD:
  Display Type:	Built-in Liquid Retina XDR Display
  Resolution:	3456 x 2234 Retina
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Automatically Adjust Brightness:	Yes
  Connection Type:	Internal
```

**Comment by wozeparrot** [comment] 2023-12-01 06:28
Duplicate of #2226

**Closed by wozeparrot** 2023-12-01 06:28 UTC
