### ISSUE TITLE
Issue on execution on MacOS M1

### ISSUE THREAD

**Issue by halowine** [tinygrad/tinygrad#2569] opened 2023-12-02 19:56 UTC
Hello, I just tried to download and install using
`git clone https://github.com/tinygrad/tinygrad.git
cd tinygrad
python3 -m pip install -e .`

When I try to execute anything I get :
`AssertionError: Error Domain=MTLLibraryErrorDomain Code=1 "Invalid library file" UserInfo={NSLocalizedDescription=Invalid library file}`

I tried to run the tests and everything fails. It stops in `tinygrad/runtime/ops_metal.py : def unwrap2(x:Tuple[T,Any]) -> T:`

**Comment by wozeparrot** [comment] 2023-12-02 20:15
Dupe of #2226

**Closed** 2023-12-02 20:15 UTC
