### ISSUE TITLE
NV=1 page fault on 3060

### ISSUE THREAD

**Issue by sixEyees** [tinygrad/tinygrad#6229] opened 2024-08-21 18:31 UTC
using a 3060
![Screenshot from 2024-08-21 23-50-23](https://github.com/user-attachments/assets/cc6e8964-9ac9-47a4-9639-48e8445f3272)

```text
from tinygrad.tensor import Tensor                                                                    
                                                                                                      
a = Tensor([1,2])                                                                  
b = Tensor([3,4])                                                            
                                                                                                      
res = a.dot(b).numpy()                                                                                                                                                                                   
```

**Comment by roelofvandijk** [comment] 2024-09-05 13:34
Does this help? https://github.com/tinygrad/tinygrad/issues/6089#issuecomment-2308426463

**Comment by nimlgen** [comment] 2024-10-19 20:50
@sixEyees, closing this issue as duplicate of #6089. If you’re experiencing the same problem, please continue the discussion there.

**Closed by nimlgen** 2024-10-19 20:50 UTC
