### ISSUE TITLE
JIT custom random has copyin error on Interpreted backends (examples/transformer.py)

### ISSUE THREAD

**Issue by tostenzel** [tinygrad/tinygrad#2829] opened 2023-12-18 22:04 UTC
python examples/transformer.py 
loss 2.32 accuracy 0.09:   2%|█▎                                                              | 1/50 [00:00<00:29,  1.64it/s]
Traceback (most recent call last):
  File "examples/transformer.py", line 31, in <module>
    train(model, X_train, Y_train, optim, 50, BS=64)
  File "/home/tobias/Documents/tinygrad/extra/training.py", line 31, in train
    loss, accuracy = train_step(x, y)
  File "/home/tobias/Documents/tinygrad/tinygrad/jit.py", line 77, in __call__
    assert len(set(get_input_replace(self.jit_cache, input_rawbuffers).values())) == len(input_rawbuffers), "some input tensors not found"
AssertionError: some input tensors not found

Looking up the values: assert 1 == 2

**Comment by chenyuxyz** [comment] 2023-12-20 16:51
which backend is this? and is it fixed on master? i cannot reproduce on METAL
<img width="1506" alt="image" src="https://github.com/tinygrad/tinygrad/assets/2525478/75465086-cca9-4625-9de4-bf5ea0e69ace">

**Comment by tostenzel** [comment] 2023-12-21 16:57
I use CPU. Below is my system info.
![Screenshot from 2023-12-21 17-53-35](https://github.com/tinygrad/tinygrad/assets/32765108/8620066b-62a1-4155-909f-9635a9932fde)

**Comment by chenyuxyz** [comment] 2023-12-21 17:15
TORCH=1 gave a more useful error message
```
  File "/Users/chenyu/code/tinygrad/tinygrad/runtime/ops_torch.py", line 49, in copyin
    def copyin(self, dest:torch.Tensor, src:memoryview): dest.copy_(torch.frombuffer(src, dtype=dest.dtype))
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The size of tensor a (128) must match the size of tensor b (49152) at non-singleton dimension 3
```

**Comment by argosopentech** [comment] 2023-12-29 22:06
I'm seeing this issue too on an Intel CPU

```
loss 5.54 accuracy 0.00:   1%|▊                                                                                   | 1/100 [00:07<12:38,  7.66s/it]
Traceback (most recent call last):
  File "/home/pj/Desktop/Tinygrad/tinytranslate/translate.py", line 100, in <module>
    train(model, X_train, Y_train, optim, TRAIN_STEPS, BS=64)
  File "/home/pj/Desktop/Tinygrad/tinygrad/extra/training.py", line 31, in train
    loss, accuracy = train_step(x, y)
  File "/home/pj/Desktop/Tinygrad/tinygrad/tinygrad/jit.py", line 86, in __call__
    self.input_replace = get_input_replace(self.jit_cache, input_rawbuffers)
  File "/home/pj/Desktop/Tinygrad/tinygrad/tinygrad/jit.py", line 25, in get_input_replace
    assert len(set(input_replace.values())) == len(input_rawbuffers), "some input tensors not found"
AssertionError: some input tensors not found

```

https://github.com/PJ-Finlay/tinytranslate/issues/4

**Comment by danielmarrama** [comment] 2024-01-06 22:21
Looking into this as I'm getting the same error as well with both `CPU=1` and `GPU=1` (CUDA). 

What seems to be happening is both input raw buffers are expected at 2 separate memory addresses but are being found at equivalent addresses. 

> found input <buf device:GPU size:384 dtype:dtypes.float> at jit_cache[299].rawbufs[6]
> found input <buf device:GPU size:384 dtype:dtypes.float> at jit_cache[301].rawbufs[1]

but the indexing:

```python
input_replace[(j,i)] = input_rawbuffers.index(a)
```

is adding the same address at .rawbufs[1]. Trying to sort out how to fix this bug.

**Comment by chenyuxyz** [comment] 2024-01-10 16:46
likely a jit random bug for interpreted backends. it works with CPU/TORCH if allow_jit=False in train function

**Comment by chenyuxyz** [comment] 2024-01-12 16:51
on `7086d77db1e06fafe44cd5bc2d678b82d3051264`, `python examples/transformer.py` works on M1 Max with CLANG/GPU/METAL/LLVM and CUDA/GPU on a 3080.

works for CPU/TORCH if disable the jit in training. i think the bug is in jitted dropout, the custom random tries to copyin a new numpy random buffer, but the destination is not matched.

can fix TORCH by changing [this line](https://github.com/tinygrad/tinygrad/blob/7086d77db1e06fafe44cd5bc2d678b82d3051264/tinygrad/runtime/ops_torch.py#L46) to `def copyin(self, dest:torch.Tensor, src:memoryview): dest.copy_(torch.frombuffer(src, dtype=dest.dtype).reshape(dest.shape))`

for cpu i get errors like `  File "/Users/chenyu/code/tinygrad/tinygrad/runtime/ops_cpu.py", line 44, in copyin
    np.copyto(dest, np.frombuffer(src, dest.dtype).reshape(dest.shape))
ValueError: assignment destination is read-only`

i think we use this issue to track the jit random bug, and hopeful someone can find a minimal repro. other backend issue can be a separate issue

**Comment by fijal** [comment] 2024-02-15 16:52
This one is no longer relevant without CPU backends (but I can't close it)

**Comment by chenyuxyz** [comment] 2024-03-12 15:49
closing as stale, no Interpreted backends now

**Closed by chenyuxyz** 2024-03-12 15:49 UTC
Labels: bug
