### ISSUE TITLE
whisper test flaky on mac

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#2399] opened 2023-11-23 17:00 UTC
Fails only if you run all the tests

`PYTHONPATH="." pytest`

Seems order dependent, and doesn't seem like `train` or `no_grad`

```
FAILED test/models/test_whisper.py::TestWhisper::test_transcribe_batch12 - AssertionError: 'Could you please let me out of the box?' != 'Could you please.'
FAILED test/models/test_whisper.py::TestWhisper::test_transcribe_batch21 - AssertionError: 'a slightly longer audio file so that we ca[42 chars]gth.' != 'aense, ('
FAILED test/models/test_whisper.py::TestWhisper::test_transcribe_file1 - AssertionError: 'Could you,,,,' != 'Could you please let me out of the box?'
FAILED test/models/test_whisper.py::TestWhisper::test_transcribe_file2 - AssertionError: 'a a few few few few years' != 'a slightly longer audio file so that we can[41 chars]gth.'
FAILED test/models/test_whisper.py::TestWhisper::test_transcribe_long - AssertionError: "Just lie back and relax. Is the level of[669 chars]ime." != 'Just the last time I I, I can can. Here,[16 chars] " "'
```

**Comment by gabelerner** [comment] 2023-11-25 19:46
I don't know enough about how metal buffers work yet but after bisecting a bit:

`PYTHONPATH="." pytest test/models` it fails (can just reduce to test efficientnet + endtoend + whisper also)

if you comment out the override of `def _cached_bufkey(self, size, dtype, device)` on `MetalAllocator` to use the base classes impl, it still fails

if you replace it with `def _cached_bufkey(self, size, dtype, device): return uuid4()`, it passes

my theory is that somehow whisper's buffers are corrupted by extra data from the cached buffers when reusing. will continue looking but maybe it's an easy fix for anybody that can quickly understand the issue above.

**Comment by gabelerner** [comment] 2023-11-27 01:45
This is a smaller reproduction
```
PYTHONPATH="." pytest test/models/test_efficientnet.py::TestViT::test_chicken test/models/test_efficientnet.py::TestResNet::test_chicken test/models/test_end2end.py::TestEnd2End::test_bn_alone test/models/test_whisper.py::TestWhisper::test_transcribe_batch12
```

Note that no buffers get actually freed or released since we have plenty of mem for these tests so it all just goes into cache as `del` is called in the initial tests' tear down.

Things I tried locally to no avail:
- Adding more `Metal.synchronize()`
- Overriding `_cache_reuse_buffer` in `MetalAllocator` and zeroing it out among other things
- Messing with purgeable state and `MTLResourceHazardTrackingModeUntracked` and `commandBufferWithUnretainedReferences()` in case Metal was holding onto these somehow

**Comment by gabelerner** [comment] 2023-11-27 21:05
@chenyuxyz i'm not sure just patching the test to pass is the answer, since it works outside of Mac/Metal and the failure on Mac/Metal means that there's a problem with Mac/Metal and not the test itself.

**Comment by mmmkkaaayy** [comment] 2023-11-27 23:57
> @mmmkkaaayy is there a reason not to reset the whisper model for each test? it's a class setup now

Initializing the model for each test case would be slower and not fully test JIT paths, so I think it's better from a correctness/coverage perspective to reuse the model across test cases.

btw, regarding this issue, I'm unable to repro it at all on my M2 Max (macOS 14.1.1).

**Comment by gabelerner** [comment] 2023-11-28 21:21
@mmmkkaaayy i couldn't create an isolated failing test, but now that you reproduced, can you please try these with `python3 -m pytest test/test_ops.py test/models/test_whisper.py` and let me know the results?

1) in `runtime/lib.py` change `rawbufs = self.cached_buffers.get(self._cached_bufkey(size, dtype, device), None)` to `rawbufs = None` and it should pass for you.

2) undo what you did in (1) and add a class level var `no_cache = False` to `LRUAllocator`. Then `if self.no_cache: rawbufs = None` after the original line. Import `MetalAllocator` into the whisper tests and set `MetalAllocator.no_cache = True` there. This will essentially turn off caching but only after `test_ops` tests are done. This should pass.

2) undo what you did in (1) and (2) and go into `test_ops.py` and comment out everything after and including `test_trunc`. that should pass. then start uncommenting one by one until it fails. i don't think it matters what you uncomment as long as there's enough tests running

i tried to spot a pattern by logging how many buffers were reused/allocated and the total sizes thinking there was some limit in python, metal interface, metal itself but couldn't find anything.

**Comment by gabelerner** [comment] 2023-11-29 01:46
Also after more bisecting, I got the tests to pass by changing `self.blocks_after_start_tok = [TinyJit(block.__call__) for block in self.blocks]` to `self.blocks_after_start_tok = [(block.__call__) for block in self.blocks]` (basically removing JIT)

A lot of the prior stuff I tried in `MetalProgram` but now I'm going to take a look at `MetalGraph` and make sure it handles buffers fine

**Comment by gabelerner** [comment] 2023-11-29 02:47
Ok, I think I'm onto something even simpler. I started printing the gpu address of the buffer and it seems like the allocator is allocating new buffers at addresses of existing buffers even though they haven't been released yet.

As an example, in `LRUAllocator`, I put `self.addrs = set()` in init

Then change `__call__` to
```
  def __call__(self, size, dtype, device='0', **kwargs): # allocate
    rawbufs = self.cached_buffers.get(self._cached_bufkey(size, dtype, device), None)
    ret = self._cache_reuse_buffer(rawbufs) if rawbufs else self._alloc_buffer(size, dtype, device, **kwargs)
    if rawbufs:
      print("Reusing buffer @", ret.gpuAddress())
    else:
      print("Allocating buffer @", ret.gpuAddress())
      if ret.gpuAddress() in self.addrs:
        print(ret)
        raise RuntimeError(f"Buffer address {ret.gpuAddress()} is reused.")
      self.addrs.add(ret.gpuAddress())
    return ret
```

At the top of `free` put `print("Caching buffer @", buf.gpuAddress())` and at the top of `_free_buffer` put `print("Freeing buffer @", buf_to_free.gpuAddress())`.

When I run `PYTHONPATH="." pytest -s test/models/test_efficientnet.py::TestViT::test_chicken`, I get:
<img width="884" alt="image" src="https://github.com/tinygrad/tinygrad/assets/241819/709b1005-37a0-490d-b949-431c14008fa9">

Note that nothing got cached/freed here, it's just allocations.

So it allocated a second buffer in the same memory region as one that already existed? This doesn't seem right since if one of these buffers gets cached here or in JIT and another allocated at the same address and both get used together in a program, that could create this sort of issue we're seeing.

**Comment by gabelerner** [comment] 2023-12-06 18:37
I just ran the full test suite on my mac after all the recent PR merges and it passed
```
========================================================== 945 passed, 71 skipped, 120 warnings in 161.37s (0:02:41) ===========================================================
```

Maybe somewhere along the way we dropped some strong ref which allowed GC and buffers weren't reused anymore.

@mmmkkaaayy can you run? if it passes we can just close the issue

**Comment by mmmkkaaayy** [comment] 2023-12-07 08:14
git bisect indicates that #2583 solved `python3 -m pytest test/test_ops.py test/models/test_whisper.py` and the full test suite for me. However, it appears that whisper and some other tests in `tests/models` may still be flaky in Metal CI.

**Comment by chenyuxyz** [comment] 2024-01-10 20:55
closing this as completed. the commands mentioned above all passed with latest master

**Closed by chenyuxyz** 2024-01-10 20:55 UTC
