### ISSUE TITLE
Getting started issue

### ISSUE THREAD

**Issue by bojanbabic** [tinygrad/tinygrad#2509] opened 2023-11-29 21:45 UTC
When I run sample code from [Quick Start](https://github.com/tinygrad/tinygrad#quick-example-comparing-to-pytorch) I get the following error:
```
AssertionError: Error Domain=MTLLibraryErrorDomain Code=1 "Invalid library file" UserInfo={NSLocalizedDescription=Invalid library file}

```

**Comment by wozeparrot** [comment] 2023-11-29 21:47
Duplicate of #2226

**Closed by wozeparrot** 2023-11-29 21:47 UTC
