### ISSUE TITLE
Error on matrix multiply with dtype float64

### ISSUE THREAD

**Issue by andresgit** [tinygrad/tinygrad#2403] opened 2023-11-23 17:58 UTC
I'm using Linux. This code:

```python
from tinygrad.tensor import Tensor
from tinygrad.helpers import dtypes
(Tensor.uniform((2,), dtype=dtypes.float64, device="GPU")@Tensor.zeros(2, dtype=dtypes.float64, device="GPU")).numpy()
```

Gives me this error:
```opencl
...
1:4:42: error: call to 'mad' is ambiguous
  data0[0] = mad((double)((val0).y),0.0f,mad((double)((val0).x),0.0f,acc0));
                                         ^~~
./opencl-c.h:7790:21: note: candidate function
float __ovld __cnfn mad(float a, float b, float c);
                    ^
./CTHeader.h:5177:38: note: candidate function
double __attribute__((overloadable)) mad(double a, double b, double c);
                                     ^
```
The kernel it generated is
```opencl
__kernel void r_2(__global double* data0, const __global float* data1) {
  float acc0 = 0.0f;
  float2 val0 = (float2)(*((__global float2*)(data1+0)));
  data0[0] = mad((double)((val0).y),0.0f,mad((double)((val0).x),0.0f,acc0));
}
```
Using float32 or CPU it works.

**Comment by geohot** [comment] 2023-11-23 20:49
Hmm the problem is that the const isn't a double. This should be pretty easy to fix.

**Comment by chenyuxyz** [comment] 2023-12-21 20:08
this is fixed on master with the dtype refactor. ast and generated kernel:

```
  0 ━┳ STORE MemBuffer(idx=0, dtype=dtypes.double, st=ShapeTracker(views=(View(shape=(1,), strides=(0,), offset=0, mask=None, contiguous=True),)))
  1  ┗━┳ SUM (1,)
  2    ┗━┳ MUL 
  3      ┣━┳ CAST (dtypes.double, False)
  4      ┃ ┗━━ LOAD MemBuffer(idx=1, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(2,), strides=(1,), offset=0, mask=None, contiguous=True),)))
  5      ┗━━ CONST ConstBuffer(val=0.0, dtype=dtypes.double, st=ShapeTracker(views=(View(shape=(2,), strides=(0,), offset=0, mask=None, contiguous=False),)))
reduced UOp count from 19 to 18
__kernel void r_2(__global double* data0, const __global float* data1) {
  double acc0 = (double)(0.0f);
  float2 val0 = (float2)(*((__global float2*)(data1+0)));
  float alu0 = mad((float)((double)((val0).y)),0.0f,mad((float)((double)((val0).x)),0.0f,(float)(acc0)));
  acc0 = (double)(alu0);
  data0[0] = acc0;
}
```

**Closed by chenyuxyz** 2023-12-21 20:08 UTC
Labels: bug
