### ISSUE TITLE
tinyllama doesn't output correctly

### ISSUE THREAD

**Issue by r3sist-uniq** [tinygrad/tinygrad#2228] opened 2023-11-07 06:16 UTC
Tried adding the [tinyllama](https://github.com/jzhang38/TinyLlama) config through #2170, expanded this config to include max_seq_len.  

`{"dim": 2048, "multiple_of": 256, "n_heads": 32, "n_kv_heads": 4,"max_seq_len": 2048,  "n_layers": 22, "norm_eps": 1e-05, "vocab_size": 32000}`

The tinyllama config.json file could be found [here](https://huggingface.co/PY007/TinyLlama-1.1B-intermediate-step-240k-503b/blob/main/config.json). 

The weight loading is being done properly, I confirmed this by manually loading weights through torch, and also np.asserting after the weight loading. 

The outputs (especially with temp=0) are not right. The huggingface inference seems to produce way better outputs. Couldn't find the bug, it seems to be subtle, most probably in the [llama.py](https://github.com/tinygrad/tinygrad/blob/master/examples/llama.py) implementation. 

Outputs from tinygrad with `CUDA=1 python3 ./examples/llama.py --count=50  --temperature=0.0 --prompt="where do you live?" --size="1B" --gen=tiny --model='./model.safetensors'` (can use this command after updating the config dictionary and LLAMA_SUFFIX inside llama.py)

![image](https://github.com/tinygrad/tinygrad/assets/72573738/6a6c9b75-7abf-4475-9731-2aad957e098c)

It could be related to post processing, but not sure about that. I tried comparing the outputs of each transformer block (there are 22 in tinyllama) from tinygrad and huggingface (torch). Using just the main `Transformer` class in llama.py. And Found the following 

1. The embedding (tok_embeddings) produces the same outputs, from both tinygrad and huggingface. This agains confirm, atleast the weight loading is being done properly. 
2. The model produces a somewhat better output than above for the same prompt without adding the "bos" token in the beginning. 
3. Suppose the input to the model is 5 tokens, the output of each transformer block in that case would be of shape (1,5,2048). For each transformer block, the outputs for the first token is the same, the rest of the outputs for the 4 tokens are different. And this is without any padding. This may hint the problem could be in the attention computation. As an example, the output of the 3rd transformer block (of shape 1,5,2048) is the same as the huggingface's output at the outputs for the first token (i.e at the index [0][0])
![image](https://github.com/tinygrad/tinygrad/assets/72573738/7215ed49-5e7c-4853-8617-e40898835b28)
This is the same for every transformer block EXCEPT the last one (which is the 22nd block)

**Comment by chenyuxyz** [comment] 2023-11-20 18:42
i think the issue is that our conversion script from huggingface format to fb llama is incorrect

our converter only swap the names (https://github.com/tinygrad/tinygrad/blob/c4cc4966ed9c44112036dd48da4e838d0542c9af/examples/llama.py#L245), but 
the llama to hf convert also permutes the q and k value. https://github.com/huggingface/transformers/blob/f18c95b49cbb675764f0cd19b56fb70f39a62bb2/src/transformers/models/llama/convert_llama_weights_to_hf.py#L122

that kinda explains why the first value matches but not the rest (permuted) does not

to correctly run tinyllama inference would require fixing the conversion, and also make sure the output matches the huggingface output with same prompt and temperature=0.

**Comment by chenyuxyz** [comment] 2023-11-22 16:16
fixed in #2374

**Closed by chenyuxyz** 2023-11-22 16:16 UTC
Labels: bug, usage/example, bounty
