### ISSUE TITLE
ROCm 6.0 broke llama

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#2985] opened 2024-01-03 00:28 UTC
There's some hang while loading the buffers, happens with both GPU and HIP

**Comment by geohot** [comment] 2024-01-03 17:30
The hang is at:

```
:3:devprogram.cpp           :2686: 82414352781 us: [pid:54228 tid:0x7ff7831d9000] Using Code Object V5.
:3:devprogram.cpp           :2686: 82414355504 us: [pid:54228 tid:0x7ff7831d9000] Using Code Object V5.
[hsaKmtAllocMemory] node 1
[hsaKmtMapMemoryToGPUNodes] address 0x7ff6de54c000 number of nodes 1
[hsaKmtAllocMemory] node 0
bind_mem_to_numa mem 0x7ff6de548000 flags 0x40 size 0x3000 node_id 0
[hsaKmtMapMemoryToGPUNodes] address 0x7ff6de548000 number of nodes 6
```

So something to do with 6 GPUs

Generate with `AMD_LOG_LEVEL=4 HSAKMT_DEBUG_LEVEL=7`

**Comment by fenfir** [comment] 2024-01-09 12:34
I am getting the same with a single 7900 XTX

```
:3:devprogram.cpp           :2686: 58641034338 us: [pid:73398 tid:0x7f037a363040] Using Code Object V5.
[hsaKmtAllocMemory] node 1
[hsaKmtMapMemoryToGPUNodes] address 0x7f0368042000 number of nodes 1
[hsaKmtAllocMemory] node 0
bind_mem_to_numa mem 0x7f036803e000 flags 0x40 size 0x3000 node_id 0
[hsaKmtMapMemoryToGPUNodes] address 0x7f036803e000 number of nodes 1
```

**Comment by fenfir** [comment] 2024-01-09 13:03
I was able to bisect it down to this commit 12fa8461223e39d40c3ed73802eee1d6efe52cc0

**Comment by fenfir** [comment] 2024-01-09 17:57
The behavior is the same with 6.0.0 and 5.7.0

Setting `LD_LIBRARY_PATH=/opt/rocm-5.7.0` yields the same result. Unfortunately, I don't know what the next step would be, I tracked it down to where it calls `clCreateKernel` from `gpuctypes` which I think means the problem is earlier in the chain, but I'm not sure where to look for that.

**Comment by chenyuxyz** [comment] 2024-01-09 18:12
i think this is fixed on tinybox with https://github.com/tinygrad/tinygrad/pull/2992

**Closed** 2024-01-23 17:04 UTC
